<!DOCTYPE html>
<html>
<head>
<?php echo $this->headTitle('根项目管理'); ?>
<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
<meta http-equiv="description" content="根项目管理">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<script type="text/javascript">
var baseUrl='<?php echo $this->baseUrl();?>';
</script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/assets/mikoUI/skins/mikoui-icons.css" />
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/jquery/jquery-1.7.2.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/plugins/cookie/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/js/client.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/mikoUI/js/mikoui.all.js"></script>
<script type="text/javascript">
var mainGrid=null;
$(function(){
	$('#mainGrid').mikoGrid({
		title:'全部根项目',
		toolbar:{
			items:[{
				text:'新建',icon:'add',click:function(item){
					openDialog('<?php echo $this->baseUrl();?>/project/project/add-project?nodeType=R&parentNode=000000000000','新建项目');
				}
			},{
				text:'其他',icon:'save'
			}]
		}
	});
});
function openDialog(url,title){
	$.mikoDialog.open({
		top:10,
		height:400,
		width:620,
		title:title,
		url:url,
		isResize:true,
		slide:true
	});
}
</script>
<style type="text/css">
body { margin:0; padding:0; }
</style>
</head>
<body>
<div id="mainGrid"></div>
</body>
</html>