<!DOCTYPE html>
<html>
<head>
<?php echo $this->headTitle('工作流模板管理'); ?>
<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
<meta http-equiv="description" content="工作流模板管理">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<script type="text/javascript">
var baseUrl='<?php echo $this->baseUrl();?>';
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/jquery/jquery-1.7.2.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/plugins/cookie/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/js/client.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/mikoUI/js/mikoui.all.js"></script>
<!-- JQuery UI -->
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/assets/jquery-ui/jquery-ui-1.10.3.custom.min.css">
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/jquery-ui/jquery-ui.min.js"></script>
<script type="text/javascript">
$(function() {
    $('#sortable').sortable();
    $('#sortable').bind('click',function(){
        console.log('AAA');
    });
});
</script>
<style>  
#sortable { list-style-type: none; margin: 0; padding: 0; width: 250px; }  
#sortable li { margin: 0 3px 3px 3px; padding: 0.4em; padding-left: 1.5em; font-size: 1.4em; height: 18px; }  
#sortable li span { position: absolute; margin-left: -1.3em; }  </style>
</head>
<body>
<ul id="sortable">
<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>item1</li>
<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>item2</li>
<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>item1</li>
<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>item2</li>
<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>item1</li>
<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>item2</li>
<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>item1</li>
<li class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>item2</li>
</ul>
</body>
</html>