<!DOCTYPE html>
<html>
<head>
<?php echo $this->headTitle('项目明细'); ?>
<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
<meta http-equiv="description" content="项目明细">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<script type="text/javascript">
var baseUrl='<?php echo $this->baseUrl();?>';
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/jquery/jquery-1.7.2.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/plugins/cookie/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/js/client.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/mikoUI/js/mikoui.all.js"></script>
<script type="text/javascript">
var groupicon = "<?php echo $this->baseUrl();?>/assets/mikoUI/skins/icons/communication.gif";
var form1=null;
var flistData=[{
	name:'好莱坞'
},{
	name:'喜洋洋'
},{
	name:'赛文奥特曼'
}];

$(function(){
	$('#form1').mikoForm({
		inputWidth: 110, labelWidth: 90, space: 40, labelAlign:'right',
		fields:[{
			label:'项目号',name:'f00',type:'text',width:100,space:0,group:'基本信息',
			groupicon: groupicon,options:{disabled:true}
		},{
			label:'是否锁定',name:'d01',type:'text',newline:false,width:50,labelWidth:70,space:0,options:{disabled:true}
		},{
			label:'当前状态',name:'d02',type:'text',newline:false,width:100,labelWidth:70,options:{disabled:true}
		},{
			label:'项目名称',name:'f01',type:'text',width:350
		},{
			label:'项目描述',name:'f02',type:'textarea',width:400
		},{
			label:'创建日期',name:'d03',type:'text',width:100,space:0,options:{disabled:true}
		},{
			display:'预估启动日期',name:'f03',type:'date',newline:false,labelWidth:95,space:0,
			options:{initValue:'<?php $estimateStartDate=strval($this->project->estimateStartDate); 
			echo substr($estimateStartDate,0,4).'-'.substr($estimateStartDate,4,2).'-'.substr($estimateStartDate,6,2); ?>'} //setData无法读取
		},{
			label:'预估天数',name:'f04',type:'spinner',newline:false,labelWidth:70,options:{type:'int'}
		},{
			label:'创建人',name:'d04',type:'text',width:100,space:0,options:{disabled:true}
		},{
			label:'负责人',name:'f05',type:'combobox',newline:false,labelWidth:60,textField:'userName',
			editor:{
				selectBoxWidth:320,
				selectBoxHeight:230,
				textField:'userName',
				valueField:'userID',
				slide:true,
				grid:{
					url:'<?php echo $this->baseUrl();?>/system/user/query-valid-user',
					pageSize:5,
					pageSizeOptions:[5,10,20],
					columns:[{
						display:'用户编号',name:'userID',width:60
					},{
						display:'姓名',name:'userName',width:110
					},{
						display:'用户角色',name:'roleName',width:100
					}]
				},
				condition:{fields:[{ name:'keyword',label:'关键字',width:90}]}
			}
		},{
			name:'c01',type:'checkboxlist',newline:true,
			options:{textField:'name',data:flistData,rowSize:1},
			group:'文件列表',groupicon: groupicon
		},{
			
		},{
			name:'f11',type:'hidden',initValue:'<?php echo $this->params['nodeType']; ?>'
		},{
			name:'f12',type:'hidden',initValue:'<?php echo $this->params['parentNode']; ?>'
		},{
			name:'f13',type:'hidden',initValue:'<?php echo $this->params['rootNode']; ?>'
		}]
	});
	<?php if($this->project->lockedStatus==0 && intval(substr($this->project->flag,0,1))<2):?>
	$('#saveButton').mikoButton({
		width:90,
		click:function(){
			var formData=form1.getData();
			//验证参数
			if(formData.f01.length<3 || formData.f01.length>100) { msg('项目名称字数应在3-100之间',180); return;}
			//日期组件只能取到locale格式的日期，需格式化
			var f03=null;
			if(formData.f03 != null){
				var date1=new Date(formData.f03);
				f03=date1.getFullYear()*10000+(date1.getMonth()+1)*100+date1.getDate();
			}
			if(formData.f04<=0) { msg('预估天数应大于0'); return;}
			if(formData.f05==null || formData.f05=='') { msg('负责人不能为空'); return;}
			var f05=formData.f05+'|'+formData.userName;
			$.post('<?php echo $this->baseUrl();?>/project/project/add-project', 
				{ f01:formData.f01, f02:formData.f02, f03:f03, f04:formData.f04,f05:f05,
				f11:formData.f11, f12:formData.f12, f13:formData.f13},
				function(data){
					if(data == '0000') window.location.href='<?php echo $this->baseUrl();?>/redirect/success';
				});
		}
	});
	$('#saveButton').bind({
		'ajaxStart':function(){ $(this).attr('disabled',true); },
		'ajaxStop':function(){ $(this).attr('disabled',false); }
	});
	$('#uploadFileButton').mikoButton({
		width:90,
		click:function(){
			alert('OK');
		}
	});
	$('#downloadFileButton').mikoButton({
		width:90,
		click:function(){
			alert('OK');
		}
	});
	$('#deleteFileButton').mikoButton({
		width:90,
		click:function(){
			alert('OK');
		}
	});
	<?php endif;?>
	<?php if($this->project->lockedStatus==0 && intval(substr($this->project->flag,0,1))==2):?>
	$('#restartButton').mikoButton({
		width:90,
		click:function(){
			alert('restart');
		}
	});
	<?php endif;?>
	$('#lockButton').mikoButton({
		width:90,
		click:function(){
			alert('OK');
		}
	});
	<?php if($this->project->lockedStatus==0 && substr($this->project->flag,0,1)=='0'):?>
	$('#submitButton').mikoButton({
		width:90,
		click:function(){
			alert('submitted');
		}
	});
	$('#cancelButton').mikoButton({
		width:90,
		click:function(){
			alert('canceled');
		}
	});
	<?php endif;?>
	<?php if($this->project->lockedStatus==0 && substr($this->project->flag,0,1)=='1'):?>
	$('#newReqButton').mikoButton({
		width:90,
		click:function(){
			alert('new requirement');
		}
	});
	$('#closeButton').mikoButton({
		width:90,
		click:function(){
			alert('closed');
		}
	});
	<?php endif;?>
	form1=$.mikoui.get('form1');
	//设置表单值
	form1.setData({
		f00:'<?php echo $this->project->projectCode; ?>',
		d01:'<?php echo $this->project->lockedStatus==0 ? '开启' : '已锁'; ?>',
		d02:'<?php echo $this->project->currentStatus; ?>',
		f01:'<?php echo $this->project->projectName; ?>',
		f02:'<?php echo $this->project->description; ?>',
		d03:'<?php $createDate=strval($this->project->createDate); 
		echo substr($createDate,0,4).'-'.substr($createDate,4,2).'-'.substr($createDate,6,2); ?>',
		f04:'<?php echo $this->project->estimateDuration; ?>',
		d04:'<?php echo $this->project->creatorName; ?>',
		f05:'<?php echo $this->project->responsibleID; ?>',
		userName:'<?php echo $this->project->responsibleName; ?>'
	});
});
function msg(content,width){
	$('#formTip').mikoTip({content:content,width:width});
	setTimeout(function(){
		$('#formTip').mikoHideTip();
	},3000);
}


</script>
<style type="text/css">
body { margin:0; padding:10px; }
#formTip { float:left; margin-top:120px; }
.btnGrp { margin-top:0px; height:25px;}
</style>
</head>
<body>
<div class="btnGrp">
<?php if($this->project->lockedStatus==0 && intval(substr($this->project->flag,0,1))<2):?>
<button id="saveButton">保存项目</button>
<?php endif;?>
<?php if($this->project->lockedStatus==0 && intval(substr($this->project->flag,0,1))==2):?>
<button id="restartButton">重启项目</button><!-- 重启是关闭的逆操作，需要父项目重启后才能启动当前项目 -->
<?php endif;?>
<button id="lockButton"><?php echo $this->project->lockedStatus==0 ? '锁定项目' : '解锁项目'; ?></button>
<?php if($this->project->lockedStatus==0 && substr($this->project->flag,0,1)=='0'):?>
<button id="submitButton">启动项目</button><!-- 启动项目后才能新建需求 -->
<button id="cancelButton">撤销项目</button><!-- 项目取消后需到项目回收站才能恢复 -->
<?php endif;?>
<?php if($this->project->lockedStatus==0 && substr($this->project->flag,0,1)=='1'):?>
<button id="newReqButton">新建需求</button>
<button id="closeButton">关闭项目</button><!-- 只有子项目全部关闭后才能关闭当前项目 -->
<?php endif;?>
</div>
<?php if($this->project->lockedStatus==0 && intval(substr($this->project->flag,0,1))<2):?>
<div class="btnGrp"><button id="uploadFileButton">上传文件</button>
<button id="downloadFileButton">下载文件</button>
<button id="deleteFileButton">删除文件</button></div>
<?php endif;?>
<div id="formTip"></div>
<div id="form1"></div> 
</body>
</html>