<!DOCTYPE html>
<html>
<head>
<?php echo $this->headTitle('团队管理'); ?>
<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
<meta http-equiv="description" content="团队管理">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<script type="text/javascript">
var baseUrl='<?php echo $this->baseUrl();?>';
</script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/assets/mikoUI/skins/mikoui-icons.css" />
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/jquery/jquery-1.7.2.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/plugins/cookie/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/js/client.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/mikoUI/js/mikoui.all.js"></script>
<script type="text/javascript">
$(function(){
	$('#teamGrid').mikoGrid({
		url:,
		delayLoad:true,
		rownumbers:true,
		columns:[{
			display:''
		},{
		},{
		},{
		},{
		}],
		toolbar: { items: [{ text: '高级查询',icon: 'search2',click:function(){
		}}]}
	});
};
</script>
</head>
<body>
<div id="teamGrid"></div>
</body>
</html>