<!DOCTYPE html>
<html>
<head>
<?php echo $this->headTitle('团队管理'); ?>
<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
<meta http-equiv="description" content="团队管理">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<script type="text/javascript">
var baseUrl='<?php echo $this->baseUrl();?>';
</script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/assets/mikoUI/skins/mikoui-icons.css" />
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/jquery/jquery-1.7.2.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/plugins/cookie/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/js/client.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/mikoUI/js/mikoui.all.js"></script>
<script type="text/javascript">
var g=null;
var teamStatus=[{value:'1',text:'有效'},{value:'0',text:'无效'}];
$(function(){
	$('#teamListGrid').mikoGrid({
		url:baseUrl+'/project/team/query-team-list',
		enabledEdit: true, 
		clickToEdit:false,
		title:'团队列表',
		columns:[{
			display:'编号',name:'teamID',width:50
		},{
			display:'团队名称',name:'teamName',width:200,editor:{type:'text'}
		},{
			display:'描述',name:'description',width:250,editor:{type:'text'}
		},{
			display:'负责人',name:'responsibleID',width:80,textField:'responsibleName',
			editor:{type:'select',
				selectBoxWidth:320,
				selectBoxHeight:240,
				textField:'userName',
				valueField:'userID',
				slide:true,
				grid:{
					url:baseUrl+'/system/user/query-valid-user',
					pageSize:5,
					pageSizeOptions:[5,10,20],
					columns:[{
						display:'用户编号',name:'userID',width:60
					},{
						display:'姓名',name:'userName',width:110
					},{
						display:'用户角色',name:'roleName',width:100
					}]
				},
				condition:{fields:[{ name:'keyword',label:'关键字',width:90}]}
			}
		},{
			display:'创建人',name:'creatorName',width:80
		},{
			display:'创建时间',name:'createTime',width:150
		},{
			display:'状态',name:'validStatus',width:50,
			render:function(item){ return item.validStatus==1 ? '有效' : '无效'},
			editor:{type:'select',data:teamStatus,valueField:'value'}
		},{
			display:'操作',width:100,render:function(rowdata, rowindex, value){
				var h = "";
                if (!rowdata._editing && rowdata.teamID)
                {
                    h += "<a href='javascript:beginTeamGridEdit(" + rowindex + ")'>修改</a> ";
                }
                else
                {
                    h += "<a href='javascript:endTeamGridEdit(" + rowindex + ")'>提交</a> ";
                    h += "<a href='javascript:cancelTeamGridEdit(" + rowindex + ")'>取消</a> "; 
                }
                return h;
			}
		}],
		toolbar:{items:[{text:'新建团队',icon:'add',click:function(){
			g.addEditRow();
		}}]},
		detail:{
			onShowDetail:f_showMember,
			height:200
		},
		onError:function(a,b){ 
			//出错处理 
		}
	});
	g=$('#teamListGrid').mikoGetGridManager();
});
function beginTeamGridEdit(rowid) { 
    g.beginEdit(rowid);
}
function cancelTeamGridEdit(rowid) { 
    g.cancelEdit(rowid);
}
function endTeamGridEdit(rowid)
{
	var oldrow=g.getRow(rowid);
	var rowdata=g.getEditRow(rowid);
	if(rowdata.teamName==''){
		$.mikoDialog.warn('团队名称不能为空');
		return;
	}
	if(rowdata.validStatus==''){
		$.mikoDialog.warn('状态不能为空');
		return;
	}
	var responsible='';
	if(/^(\d+)$/.test(rowdata.responsibleID)) responsible=rowdata.responsibleID+'|'+rowdata.responsibleName;
    $.post(baseUrl+'/project/team/modify-team',{
        p0:oldrow.teamID || 0,p1:rowdata.teamName,p2:rowdata.description,p3:responsible,p4:rowdata.validStatus
    },function(data){
        if(data=='0000'){
        	g.endEdit(rowid);
        	if(!oldrow.teamID) g.reload();
        	tip('信息提示','保存成功');
        }else{
        	tip('信息提示','保存失败');
        }
    });
}
function f_showMember(row, detailPanel,callback)
{
	if(row.teamID===undefined) return;
	var editRowFlag=false;
	var editRowIndex=null;	//追踪编辑行的行号便于保存
    var grid = document.createElement('div'); 
    $(detailPanel).append(grid);
    var g2=$(grid).css('margin-top',5).mikoGrid({
    	title:row.teamName+' 成员管理',
        url:baseUrl+'/project/team/query-member-list/tid/'+row.teamID,
        width:530,
        height:220,
        rownumbers:true,
        checkbox:true,
        usePager:false,
        enabledEdit: true, 
        clickToEdit:false,
        columns:[{
        	display:'成员姓名',name:'userID',width:100,textField:'userName',
        	editor:{type:'select',
				selectBoxWidth:320,
				selectBoxHeight:240,
				textField:'userName',
				valueField:'userID',
				slide:true,
				grid:{
					url:baseUrl+'/project/team/query-valid-user/tid/'+row.teamID,
					pageSize:5,
					pageSizeOptions:[5,10,20],
					columns:[{
						display:'用户编号',name:'userID',width:60
					},{
						display:'姓名',name:'userName',width:110
					},{
						display:'用户角色',name:'roleName',width:100
					}]
				},
				condition:{fields:[{ name:'keyword',label:'关键字',width:90}]}
			}
        },{
        	display:'担任角色',name:'roleDesc',width:200,editor:{type:'text'}
        },{
        	display:'加入时间',name:'createTime',width:150,
        	render:function(rowdata, rowindex, value){
            	if(!rowdata.createTime) editRowIndex=rowindex;
            	return rowdata.createTime || '';
            }
        }],
        isScroll: false,
        onAfterShowData: callback,
        frozen:false,
        toolbar:{items:[{
            text:'刷新',icon:'refresh',click:function(){
                g2.reload();
            }
        },{line:true},{
            text:'添加成员',icon:'add',click:function(){
                //防止插入多行
                if(!editRowFlag){
                	g2.addEditRow();
                    editRowFlag=true;
                }
            }
        },{line:true},{
            text:'保存成员',icon:'save',click:function(){
                if(editRowFlag){
                	var rowdata=g2.getEditRow(editRowIndex);
                	if(!/^(\d+)$/.test(rowdata.userID)){
                		$.mikoDialog.warn('保存前请选择成员');
                    	return;
                    }
                    $.post(baseUrl+'/project/team/add-member',
                    {p1:row.teamID,p2:rowdata.userID,p3:rowdata.userName,p4:rowdata.roleDesc},
                    function(data){
                    	if(data=='0000'){
                        	g2.endEdit(editRowIndex);
                        	editRowFlag=false;
                        	editRowIndex=null;
                        	g2.reload();
                        	tip('信息提示','保存成功');
                        }else{
                        	tip('信息提示','保存失败');
                        }
                    });
                }
            }
        },{line:true},{
            text:'移除选定成员',icon:'delete',click:function(){
            	var rows=g2.getSelectedRows();
                var uids=[];
                var unames=[];
                for(var i=0;i<rows.length;i++){
                    if(rows[i].userID && /^(\d+)$/.test(rows[i].userID)){
                    	uids.push(parseInt(rows[i].userID));
                    	unames.push(rows[i].userName);
                    } 
                }
            	$.mikoDialog.confirm('确定移除'+unames.join(',')+'吗？',function(yes){
                    if(uids.length==0){
                    	$.mikoDialog.warn('请选择成员');
                    	return;
                    }
                    $.post(baseUrl+'/project/team/remove-member',
                    {tid:row.teamID,uids:uids.join(',')},
                    function(data){
                    	if(data=='0000'){
                        	g2.reload();
                        	tip('信息提示','删除成功');
                        }else{
                        	tip('信息提示','删除失败');
                        }
                    });
                });
            }
        }]}
    });  
}
function tip(title,content){
	//提示信息
	var tip=$.mikoDialog.tip({  title: title,content:content });
	setTimeout(function(){
		if(tip)	tip.hide();
	},3000);
}
</script>
<style type="text/css">
body {
	margin: 0;
	padding: 0;
}
a {
	color: #111;
}
a:hover {
	color: #999;
}
</style>
</head>
<body>
<div id="teamListGrid"></div>
</body>
</html>