<!DOCTYPE html>
<html>
<head>
<?php echo $this->headTitle('需求查询'); ?>
<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
<meta http-equiv="description" content="需求查询">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<script type="text/javascript">
var baseUrl='<?php echo $this->baseUrl();?>';
</script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/assets/mikoUI/skins/mikoui-icons.css" />
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/jquery/jquery-1.7.2.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/plugins/cookie/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/js/client.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/assets/mikoUI/js/mikoui.all.js"></script>
<script type="text/javascript">
var g=null,g2=null;
var cb1=null,cb2=null;
$(function(){
	$('#rootProject').mikoComboBox({
		isMultiSelect:false,
		isShowCheckBox:false,
		selectBoxWidth:520,
		selectBoxHeight:210,
		valueField:'projectCode',
		textField:'projectName',
		valueFieldID:'rootProjectCodeFieldID',
		slide:true,
		grid:{
			url:baseUrl+'/project/main/query-root-project-snapshot',
			pageSize:5,
			pageSizeOptions:[5,10],
			columns:[{
				display:'项目名称',name:'projectName',width:160
			},{
				display:'项目编号',name:'projectCode',width:120
			},{
				display:'创建人',name:'creatorName',width:60
			},{
				display:'创建日期',name:'createDate',width:80
			},{
				display:'子块数',name:'pCnt',width:60
			}]
		},
		onSelected:function(selectedValue){
			if(cb2){
				g2=cb2.getGrid();
				if(g2){
					g2.setParm('code',$('#rootProjectCodeFieldID').val());
					g2.setParm('condition','[]');
					g2.changePage('first');
					g2.reload();
				}
				cb2.setText('');
			}
		}
	});
	$('#projectTree').mikoComboBox({
		isMultiSelect:false,
		isShowCheckBox:false,
		selectBoxWidth:450,
		selectBoxHeight:210,
		valueField:'projectCode',
		textField:'projectName',
		valueFieldID:'childProjectCodeFieldID',
		slide:true,
		grid:{
			url:baseUrl+'/project/req/query-project-tree',
			usePager:false,
			rownumbers:true,
			columns:[{
				display:'项目编码',name:'projectCode',id:'projectCode',width:150
			},{
				display:'项目名称',name:'projectName',width:180
			},{
				display:'需求数量',name:'reqCount',width:70
			}],
			tree:{
				columnId:'projectCode',
				idField:'projectCode',
				parentIDField:'parentNode',
				isExpand: false
			},
			onAfterShowData:function(data){
				g2=cb2.getGrid();
				g2.collapseAll();	//收缩全部
			}
		},
		onBeforeOpen:function(){
			var code=$('#rootProjectCodeFieldID').val();
			if(code==''){
				$.mikoDialog.warn('请先选择根项目');
				return false;
			}else{
				g2=cb2.getGrid();
				if(!g2){
					cb2.setParm('code',code);
				}
			}
		},
		onSelected:function(value){
			if(g){
				g.setParm('code',value);
				g.reload();
			}
		}
	});
	$('#reqListGrid').mikoGrid({
		url:baseUrl+'/project/req/query-req-list',
		delayLoad:true,
		rownumbers:true,
		enabledSort:false,
		columns:[{
			display:'编号',name:'requirementID',width:50
		},{
			display:'名称',name:'requirementName',width:260
		},{
			display:'创建人',name:'creatorName',width:70
		},{
			display:'指派人',name:'distributorName',width:70
		},{
			display:'评审人',name:'reviewerName',width:70
		},{
			display:'优先级',name:'priority',width:50
		},{
			display:'创建日期',name:'createDate',width:80
		},{
			display:'当前状态',name:'currentStatus',width:60
		},{
			display:'操作',columns:[{
				display:'明细',name:'',width:50,render:function(rowdata,rowindex,value){
					var url='<?php echo $this->baseUrl();?>/project/req/query-req-detail/id/'+rowdata.requirementID;
					var title='项目需求明细';
					return '<a href="#" onclick="javascript:openDialog(\''+url+'\',\''+title+'\',530,800);">查看</a>';
				}
			},{
				display:'报表',name:'',width:50
			}]
		}],
		toolbar: { items: [{ text: '高级查询',icon: 'search2',click:function(){
			if(g2==null){
				$.mikoDialog.warn('请先选择需求对应的项目');
				return;
			}
			$.mikoDialog.open({
				top:30,
				height:320,
				width:500,
				title:'高级查询',
				target: $("#target1"),
				buttons:[{
					text: '确定', onclick: function (item, dialog) {
						var sortValues=miko.get('listbox2').getValue();
						var descFlag=miko.get('descFlag').getValue();
						var nameValue=miko.get('reqName').getValue();
						var startdateValue=miko.get('reqStartDate').getValue();
						var enddateValue=miko.get('reqEndDate').getValue();
						var statusValue=miko.get('reqStatus').getValue();
						if((startdateValue==null && enddateValue!=null) || (startdateValue!=null && enddateValue==null)){
							$.mikoDialog.warn('请同时选择或不选起讫日期');
							return;
						}
						if(g){
							var startdate='',enddate='';
							if(startdateValue!=null && startdateValue!=''){
								var date1=new Date(startdateValue);
								startdate=date1.getFullYear()*10000+(date1.getMonth()+1)*100+date1.getDate();
							}
							if(enddateValue!=null && enddateValue!=''){
								var date2=new Date(enddateValue);
								enddate=date2.getFullYear()*10000+(date2.getMonth()+1)*100+date2.getDate();
							}
							g.setParm('sort',sortValues);
							g.setParm('p1',nameValue);
							g.setParm('p2',startdate);
							g.setParm('p3',enddate);
							g.setParm('p4',statusValue);
							g.setParm('p6',descFlag);
							g.reload();
						}
					},cls:'l-dialog-btn-highlight' 
				},{
					text:'重置',onclick:function(item, dialog){
						moveAllToLeft();
						miko.get('reqName').setValue('');
						miko.get('reqStartDate').clear();
						miko.get('reqEndDate').clear();
						miko.get('reqStatus').setValue('');
					}
				}]
			});
		}}]}
	});
	$('#selectButton').mikoButton({
		width:90,
		click:function(){
			alert('OK');
		}
	});
	g=$('#reqListGrid').mikoGetGridManager();
	cb1=$('#rootProject').mikoGetComboBoxManager();
	cb2=$('#projectTree').mikoGetComboBoxManager();

	//初始化对话框表单
	$("#listbox1,#listbox2").mikoListBox({
        isShowCheckBox: true,
        isMultiSelect: true,
        height: 110
    });
    var data = [
            { text: '编号', id: '1' },
            { text: '名称', id: '2' },
            { text: '创建人', id: '3' },
            { text: '指派人', id: '4' },
            { text: '评审人', id: '5' },
            { text: '优先级', id: '6' },
            { text: '创建日期', id: '7' },
            { text: '当前状态', id: '8' }
    ];
    miko.get("listbox1").setData(data);
    $('#descFlag').mikoCheckBox();
    $('#reqName').mikoTextBox({ width:120 });
    $('#reqStartDate').mikoDateEditor({ width:120 });
    $('#reqEndDate').mikoDateEditor({ width:120 });
    $('#reqStatus').mikoComboBox({ 
        width:120,
        valueFieldID:'reqStatusValue',
        data:[{ text:'初始值',id:'0'},{ text:'提交审核',id:'1'},{ text:'退回未提交',id:'2'},
              { text:'通过审核',id:'3'},{ text:'已立项',id:'4'},{ text:'提交验收',id:'5'},
              { text:'验收退回',id:'6'},{ text:'通过验收',id:'7'},{ text:'已关闭',id:'8'}]
    });
});
function openDialog(url,title,height,width){
	$.mikoDialog.open({
		top:30,
		height:height,
		width:width,
		title:title,
		url:url,
		showMax:true,
		showMin:false,
		isResize:true,
		slide:true
	});
}
//////////////////////////////////////////////////////////////////////
function moveToLeft()
{
    var box1 = miko.get("listbox1"), box2 = miko.get("listbox2");
    var selecteds = box2.getSelectedItems();
    if (!selecteds || !selecteds.length) return;
    box2.removeItems(selecteds);
    box1.addItems(selecteds);
}
function moveToRight()
{
    var box1 = miko.get("listbox1"), box2 = miko.get("listbox2");
    var selecteds = box1.getSelectedItems();
    if (!selecteds || !selecteds.length) return;
    box1.removeItems(selecteds);
    box2.addItems(selecteds);
}
function moveAllToLeft()
{ 
    var box1 = miko.get("listbox1"), box2 = miko.get("listbox2");
    var selecteds = box2.data;
    if (!selecteds || !selecteds.length) return;
    box1.addItems(selecteds);
    box2.removeItems(selecteds); 
    box2.clear();
}
function moveAllToRight()
{ 
    var box1 = miko.get("listbox1"), box2 = miko.get("listbox2");
    var selecteds = box1.data;
    if (!selecteds || !selecteds.length) return;
    box2.addItems(selecteds);
    box1.removeItems(selecteds);
   
}
</script>
<style type="text/css">
body { margin: 0; padding: 0; }
a { color: #111; }
a:hover { color: #999; }
label { font-weight:bold; }
#wrapper { float: left; margin: 20px 30px 20px 30px; display: inline; width: 900px; height: 600px; }
#top { float: left; margin-left: 0px; margin-top: 0px; display: inline; width: 900px; height: 30px; }
#top ul { list-style: none; }
#top ul li { float: left; margin-left: 15px; }
#main { float: left; margin-left: 0px; display: inline; width: 900px; height: 500px; border-top: solid 2px #cccccc; margin-top: 12px; padding-top: 18px; }
.l-table-edit { }
.l-table-edit-td { padding:4px; }
.l-button-submit, .l-button-reset { width:80px; float:left; margin-left:10px; padding-bottom:2px; }
.l-verify-tip { left:230px; top:120px; }
</style>
</head>

<body>
  <div id="wrapper">
    <div id="top">
      <ul>
        <li><label>根项目：</label></li>
        <li><input type="text" id="rootProject" /></li>
        <li><label>项目树：</label></li>
        <li><input type="text" id="projectTree" /></li>
        <li>
          <button id="selectButton">待定</button>
        </li>
      </ul>
    </div>
    <div id="main">
      <div id="reqListGrid"></div>
    </div>
  </div>
  <form id="dialogForm" name="dialogForm">
  <div id="target1" style="margin:3px;display:none;">
    <div>
    	<h4>自定义排序</h4>
    	<div style="margin:4px;float:left;">
    		<div id="listbox1"></div>  
     	</div>
     	<div style="margin:4px;float:left;" class="middle">
			<input type="button" onclick="moveToLeft()" value="<" />
			<input type="button" onclick="moveToRight()" value=">" />
			<input type="button" onclick="moveAllToLeft()" value="<<" />
			<input type="button" onclick="moveAllToRight()" value=">>" />
		</div>
		<div style="margin:4px;float:left;">
			<div id="listbox2"></div> 
		</div>
		<table cellpadding="0" cellspacing="0" class="l-table-edit" >
			<tr>
                <td align="right" class="l-table-edit-td"><label>是否倒序</label></td>
                <td align="left" class="l-table-edit-td"><input type="checkbox" id="descFlag"/></td>
                <td align="left"></td>
            </tr>
            <tr>
                <td align="right" class="l-table-edit-td"><label>需求名称关键字</label></td>
                <td align="left" class="l-table-edit-td"><input type="text" id="reqName"/></td>
                <td align="left"></td>
            </tr>
            <tr>
            	<td align="right" class="l-table-edit-td"><label>创建日期区间</label></td>
                <td align="left" class="l-table-edit-td"><input type="text" id="reqStartDate"/></td>
                <td align="left" class="l-table-edit-td"><input type="text" id="reqEndDate"/></td>
            </tr>
            <tr>
                <td align="right" class="l-table-edit-td"><label>状态字</label></td>
                <td align="left" class="l-table-edit-td"><input type="text" id="reqStatus"/></td>
                <td align="left"></td>
            </tr>
        </table>
	</div>
  </div>
  </form>	
</body>
</html>
